services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: api
    ports:
      - "8080:8080"
    networks:
      - urltracker
    restart: unless-stopped

  bot:
    build:
      context: ./telegram-bot
      dockerfile: Dockerfile
    container_name: bot
    depends_on:
      - api
    networks:
      - urltracker
    restart: unless-stopped

networks:
  urltracker:
    driver: bridge
